package com.plumora.api.admin.domain;

public enum AdminAction {
	USER_STATUS_UPDATED,
	USER_ROLE_UPDATED,
	BOOK_IMPORTED,
	BOOK_ARCHIVED,
	BOOK_RESTORED,
	BOOK_METADATA_UPDATED,
	REPORT_STATUS_UPDATED,
	REPORT_RESOLVED,
	REPORT_REJECTED,
	AI_SETTINGS_UPDATED
}
